_target_: src.datamodules.cifar10_datamodule.CIFAR10DataModule

data_dir: ${data_dir}CIFAR10 # data_dir is specified in config.yaml
batch_size: 64
train_val_test_split: [45_000, 5_000, 10_000]
num_workers: 4
pin_memory: True
